name: NPM Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      
      # Build and test
      - run: npm install --production
      - run: npm ci
      - run: npm test
      
      # Bump version and tag
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v5.0.18
      
      # Generate Changelog
      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: git add CHANGELOG.md && git commit -m '#patch Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"
                  
      # Push Changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Deploy npm package
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@zkoppert'

      - run: npm install --production
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

