name: NPM Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      
      # Build and test
      - run: npm install --production
      - run: npm ci
      - run: npm test
      
      # Bump version and tag
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v7.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Generate Changelog
      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push Changelog.md
        uses: alexesprit/action-update-file@master
        with:
          file-path: CHANGELOG.md
          commit-msg: patch Updated CHANGELOG.md
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Deliver npm package
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@zkoppert'

      - run: npm install --production
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      # Deploy to serverless
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
