name: NPM Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        
      - run: npm install --production
      - run: npm ci
      - run: npm test
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WITH_V: true
          
      # Sync version from tag to package.json 
      - run: git config --local user.email "Carl-the-llama@nowhere.com"
      - run: git config --local user.name "Carl Llama"
      - run: git fetch --tags
      - run: npm --no-git-tag-version version `git describe --tags`
      
      # Commit version change
      - run: git add package.json; git commit -m "Sync version number from tag"

      # Generate Changelog
      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"
                  
      # Push Changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@zkoppert'

      # Deploy npm package
      - run: npm install --production
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

