name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --production
      - run: npm ci
      - run: npm test
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WITH_V: true
      - name: Sync version from tag to package.json 
      - run: npm version `git describe --tags`
      - name: Commit files
      - run: git config --local user.email "Carl-the-llama@nowhere.com"
      - run: git config --local user.name "Carl Llama"
      - run: git commit -m "Sync version number from tag" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@zkoppert'
      - run: npm install --production
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

